#version: "3.9"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - kafka
      - python-service
    env_file:
      - ./backend/.env        # ✅ load MongoDB URI & other secrets from backend/.env
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:9092
      - PYTHON_SERVICE_URL=http://python-service:8000
    networks:
      - app-network

  python-service:
    build: ./python-service
    container_name: python-service
    ports:
      - "8000:8000"
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:3.9.2   # ✅ modern image
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:3.6.2       # ✅ modern image
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
